B1A3-study/Algorithm

Ahyeon/DFS, BFS/타겟 넘버.py

이전에 풀었던 문제였지만, 다시 풀어보니 너무 새로웠다.
승민이의 아이디어(이진트리)를 참고해서 풀었다.

solve: programmers_타겟넘버

---

Ahyeon/DFS, BFS/게임 맵 최단거리.py

전형적인 dfs/bfs 문제였지만, 역시나 구글링에 도움을 받았다..
암기해서 풀면 역시나 안 돼🤣

solve: programmers_게임 맵 최단거리

---

Mingeun/DFS, BFS/GameMap.cpp

&& || 실수하지 말자! 그리고 변수 선언 몇 개 해서 코드를 좀 더 깔끔하게 만들자

solve: programmers: 게임맵 최단거리

---

Ahyeon/Greedy/체육복.py

예전에 풀어본 문제인데,, 역시나 어려웠다.
차근차근 풀면 더 쉽게 풀 수 있을텐데 아쉽다. 다른 방법으로 또 다시 풀어봐야겠다.

solve: programmers_체육복

---

Ahyeon/Implementation/메뉴 리뉴얼.py
Ahyeon/Implementation/오픈채팅방.py

temp_order.append(list(combinations(sorted(order), i))) 에서 sorted(order)가 아닌 order로 넣어서, 마지막 테스트 케이스(["XYZ", "XWY", "WXA"] => ["WX", "XY"])와 같은 경우에서 계속 실패했다.
Counter 함수에 대해 복습해보고, list(combinations(sorted(order), i))에 대해 알 수 있어서 좋았던 문제였다.

solve: programmers_메뉴 리뉴얼

---

Mingeun/Implementation/Menu.cpp

문제가 정신 나간듯이 어렵네요.. next_permutation 이용해서 조합 구하는 부분까지는 이전에 해봤어서 했는데 구한 조합들을 집합과 같이 저장할 방법을 생각 못해서 map STL 사용하는 법 참고했습니다. map에 일단 구한 조합들 다 넣어 놓고, vector로 옮겨서 많이 선택된 코스 순으로 정렬한 뒤에 이중 for문으로 최대인 애들만 answer에 넣어줬습니다

solve_programmers_메뉴 리뉴얼

---

Ahyeon/Implementation/큰 수 만들기.py

예전에 풀어봤던 문제였지만, 푸느라 눈물이 날뻔 했다. 결국은 구글링의 도움을 받았다.. 후에 다시 풀어봐야겠다ㅠㅠ

solve: 3/18

---

SeungMin/Greedy/bigNum.cpp
SeungMin/Implmentation/openChatRoom.cpp

큰 수 찾기 : 범위와 위치 줄이고 옮겨가면서 제일 큰 수 찾기
오픈 채팅방 : istringstream 이라는 배열파싱 함수를 알게된 좋은 문제였다. map을 쓰는 법도 좀 더 익숙해진 것 같다.

sovle: 3/18

---

Mingeun/Sort/SerialNumber.cpp
Mingeun/Sort/Statistics.cpp
Mingeun/String/Palindrome.cpp
Mingeun/String/terceSpoT.cpp

팰린드롬 풀 때 너무 이상하게 풀려고 해서 고생했다... 좀만 더 생각을 깔끔히 하고 풀기 시작하는 게 좋은 것 같다. 그리고 getline으로 줄별로 받는 것도 배웠고, map 사용법도 더 익혔고 C++17에서 생긴 신기한 반복문도 배웠는데, 엄청 유용하게 쓸 수 있을 것 같다. 실수도 좀만 더 줄이면 좋을 것 같다..

Sorting & String

---

SeungMin/Sorting/Beak_1431.cpp
SeungMin/Sorting/Beak_2108.cpp
SeungMin/String/Beak_11365.cpp
SeungMin/String/Beak_15927.cpp

solve:boj_밀비급일
solve:boj_회문은 회문아니야
solve:boj_통계학
solve:boj_시리얼 넘버

solve:Sorting & String

---

Ahyeon/DFS, BFS/안전 영역.py
Ahyeon/Dynamic Programming/돌 게임.py
Ahyeon/Implementation/경비원.py

solve: 3월 마지막 주 - 1

---

Mingeun/DFS, BFS/2468_SafeArea.cpp
Mingeun/DP/9655_StoneGame.cpp
Mingeun/Implementation/2564_Guard.cpp

안전영역은 아이스크림 문제랑 비슷해서 의외로 쉽게 풀었다.. 근데 코드가 좀 지저분해서 (flag 글로벌 변수 이런거) 다른 사람 꺼 보니 bool 형태로 DFS 함수에서 리턴할 수 있게 했던데, 이런 방법을 쓰는게 좋을거같다
경비원은 그 네모를 다 펴서 수직선위에 올린다는 방식으로 생각했는데, 자꾸 이상하게 답이 안나와서(실수해서) 디버깅을 좀 여러번 했다. 마구잡이로 풀지말고 좀 더 똑똑하게 생각해서 풀도록 노력해야겠다.

solve: 3.28~3.30

---

SeungMin/DFS, BFS/safeArea.cpp
SeungMin/DynamicProgramming/BOJ_9655.cpp
SeungMin/Implmentation/Boj2564.cpp

solve: DFS, Implementation, DP

solve: 월화수 문제풀이

---

SeungMin/DynamicProgramming/BOJ_14501.cpp
SeungMin/String/BOJ_15904.cpp

문자열: 예외 상황 잘 생각해서 풀어야할듯
dp: dp는 너무 어렵네요...많은 문제 풀면서 경험 쌓기....

solve:3/31~4/1

---

Mingeun/DP/14501_Resign.cpp
Mingeun/String/15904_UCPC.cpp

solve: 03.31~04.01

---

Ahyeon/Backtracking/N과 M (1).py
Ahyeon/Greedy/A에서 B.py
Ahyeon/Greedy/신입 사원.py
Ahyeon/Implementation/쉽게 푸는 문제.py
Ahyeon/Sorting/전화번호 목록.py

백트래킹 문제가 가장 어려웠던 것 같다.
지속적으로 공부해봐야 할 것 같다.

solve: 04.02 ~ 04.06

---

Mingeun/BackTracking/15649_NnM.cpp
Mingeun/DFS, BFS/16953_AtoB.cpp
Mingeun/Greedy/1946_NewSlave.cpp
Mingeun/Implementation/1292_EasyProblem.cpp
Mingeun/Sort/5052_PhoneList.cpp

자꾸 코드 짤 때 기본적인 부분 실수하는 것 좀 고쳐야될듯... 신입사원 풀 때 그거 때문에 고생함.. 그리고 DFS, BFS 할 때 깊이 어떻게 생각할 지 둘 다 꼭 알고 있어야겠다

solve: 04.02~04.06

---

SeungMin/BackTracking/BOJ_15649.cpp
SeungMin/DFS, BFS/BOJ_16953.cpp
SeungMin/Greedy/BOJ_1946.cpp
SeungMin/Implmentation/BOJ_1292.cpp
SeungMin/Sorting/BOJ_5052.cpp

solve:4/2~4/6

---

Ahyeon/Binary Search/수 찾기.py
Ahyeon/Binary Search/숫자 카드.py
Ahyeon/Implementation/치킨 배달.py

이진 탐색 문제를 풀때, 푸는 방법을 외워서 푸는 것 같다는 느낌을 받았다.
그리고 백트래킹은 역시나 어려웠다🤣

solve: 04.07~04.10

---

SeungMin/BackTracking/BOJ_14888.cpp
SeungMin/BinarySearch/BOJ_10815.cpp
SeungMin/BinarySearch/BOJ_1920.cpp
SeungMin/Implmentation/BOJ_15686.cpp

이진탐색은 구현했는데 내장된 binary_search가 효율이 좋은가보다...
벡트래킹은 이제 조금 알것같다.
구현도 벡트래킹 느낌으로다가 풀어버림

solve:4/7~4/10

---

Ahyeon/Implementation/빗물.py

solve: 05.09

---

SeungMin/DFS, BFS/BOJ_7576.cpp
SeungMin/Greedy/BOJ_1541.cpp
SeungMin/Implmentation/BOJ_14719.cpp

처음 생각한대로 풀걸 너무 돌아가느라 시간이 오래걸렸네요..

solve:BOJ_빗물

---

Mingeun/DP/1912_ContinuousSum.cpp
Mingeun/Greedy/1541_LostParenthesis.cpp
Mingeun/Greedy/ContainerWithMostWater.cpp
Mingeun/Implementation/14500_Tetromino.cpp
Mingeun/Implementation/2870_MathHomework.cpp
Mingeun/ShortestPath/1238_Party.cpp

solve: 5.10~5.13

---

Mingeun/DP/1912_ContinuousSum.cpp
Mingeun/Greedy/1541_LostParenthesis.cpp
Mingeun/Greedy/ContainerWithMostWater.cpp
Mingeun/Implementation/14500_Tetromino.cpp
Mingeun/Implementation/2870_MathHomework.cpp
Mingeun/ShortestPath/1238_Party.cpp

Reverts B1A3-study/Algorithm#42

Revert "Revert "solve: 5.10~5.13""

---

SeungMin/DynamicProgramming/BOJ_1912.cpp
SeungMin/Greedy/Dijkstra/BOJ_1238.cpp
SeungMin/Greedy/LC_ContainerWithMostWater.cpp

BOJ_1912 : 가벼운 DP로 DP 감 잃지않기
LC : 뭔가 좀 불편한 리트코드...
B0J_1238 : vector보다 배열쓰도록 노력하기..........

solve:5/15~5/18

---

hyeonseop/DFS, BFS/boj_7576_토마토.cpp
hyeonseop/DP/boj_1912_연속합.cpp
hyeonseop/Dijkstra/boj_1238_파티.cpp
hyeonseop/Greedy/boj_1541_잃어버린괄호.cpp
hyeonseop/Greedy/leet_ContainerWithMostWater.cpp
hyeonseop/Implementation/boj_14500_테트로미노.cpp
hyeonseop/Implementation/boj_2870_수학숙제.cpp
hyeonseop/shortcut/boj_1238_파티.cpp

코딩테스트가 아직 익숙치 않아서 힘이 든다. 최대한 따라가면서 해봐야겠다.

solve:5/9~5/18

---

Ahyeon/DFS, BFS/단지번호붙이기.py
Ahyeon/Implementation/한 줄로 서기.py

solve: 5/19~5/20

---

SeungMin/DFS, BFS/BOJ_2667.cpp
SeungMin/Implmentation/BOJ_1138.cpp

solve:5/19~5/20
